### ISSUE TITLE
Start mysqld with a different user/password

### ISSUE THREAD

**Issue by yashmankad** [lestrrat/go-test-mysqld#12]
Hi,
Firstly, this is a neat little tool that takes away a lot of headache from deploying MySQL while running Go tests. After playing around this a bit more, I realized we cannot start the daemon with a custom username or password - they have to be root/"".

Is my understanding correct? If not, can you pls share details how to do this. I tried setting these options via ```mysqld.DSN(mysqltest.WithUser("foo"), mysqltest.WithPassword("passw0rd!"))``` but that doesn't work. It only spits out a dsn string for use elsewhere. And that dsn string is not very useful since the mysql daemon still expects login as root/"".

Thanks for your help.

**Comment by lestrrat** [comment]
There's no way to _portably_ create a user on MySQL other than to connect to mysql as superuser and issue a `CREATE USER` statement. So you should start an instance with this tool, connect as root and do the magic `CREATE USER` incantation, and then use `mysqld.DSN` to provide the dsn string to your tests

**Comment by yashmankad** [comment]
Makes perfect sense! Thanks for your help and lib.
